// src/features/student/placement/components/readiness/CareerRecommendations.jsx
// Displays backend-provided career recommendations with rationale, action items, and projected score impact.

import React from 'react';
import { Sparkles, ArrowRight, Zap, Info, CheckCircle } from 'lucide-react';
import { getPriorityBadge } from '../../utils/readinessHelpers';
import SkeletonLoader from '../common/SkeletonLoader';
import ErrorState from '../common/ErrorState';
import EmptyState from '../common/EmptyState';

export default function CareerRecommendations({
  recommendations = [],
  isLoading = false,
  isError = false,
  error = null,
  onRetry,
}) {
  if (isLoading) {
    return <SkeletonLoader variant="list" count={3} />;
  }

  if (isError) {
    return (
      <ErrorState
        title="Recommendations unavailable"
        message={error || 'Could not load personalized guidance.'}
        onRetry={onRetry}
      />
    );
  }

  if (!recommendations || recommendations.length === 0) {
    return (
      <EmptyState
        title="No Recommendations"
        description="Your personalized preparation guidance will appear once diagnostics are analyzed."
        icon="award"
      />
    );
  }

  return (
    <div className="card shadow-card hover:shadow-card-md transition-shadow">
      <div className="flex items-center gap-3 pb-3 mb-4 border-b border-surface-100">
        <div className="w-10 h-10 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center border border-purple-100">
          <Sparkles className="w-5 h-5" />
        </div>
        <div>
          <h3 className="section-title text-base lg:text-lg">
            Personalized Career Recommendations
          </h3>
          <p className="text-xs text-surface-500">
            Tailored action plan generated by placement analytics
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {recommendations.map((rec) => {
          const priority = getPriorityBadge(rec.priority);

          return (
            <div
              key={rec.id}
              className="p-5 rounded-2xl border border-surface-200 bg-white hover:border-primary-200 hover:shadow-xs transition-all flex flex-col justify-between"
            >
              <div>
                {/* Header: Title, Category & Priority */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h4 className="text-sm font-bold text-surface-900">
                      {rec.title}
                    </h4>
                    {rec.category && (
                      <span className="badge bg-surface-100 text-surface-600 text-2xs">
                        {rec.category}
                      </span>
                    )}
                  </div>

                  <span className={`badge px-2.5 py-0.5 text-2xs border self-start sm:self-auto ${priority.className}`}>
                    <span className={`w-1.5 h-1.5 rounded-full mr-1.5 ${priority.dot}`} />
                    {priority.label}
                  </span>
                </div>

                {/* Description */}
                <p className="text-xs text-surface-700 leading-relaxed mb-3">
                  {rec.description}
                </p>

                {/* Reason Callout */}
                {rec.reason && (
                  <div className="p-3 rounded-xl bg-surface-50 border border-surface-100 text-xs flex items-start gap-2 mb-3">
                    <Info className="w-4 h-4 text-primary-600 shrink-0 mt-0.5" />
                    <div className="text-surface-600">
                      <strong className="text-surface-800">Recruiter Rationale: </strong>
                      {rec.reason}
                    </div>
                  </div>
                )}

                {/* Action Item */}
                {rec.action && (
                  <div className="p-3 rounded-xl bg-indigo-50/50 border border-indigo-100 text-xs flex items-start gap-2">
                    <CheckCircle className="w-4 h-4 text-indigo-600 shrink-0 mt-0.5" />
                    <div className="text-indigo-950 font-medium">
                      <span className="font-bold text-indigo-700">Immediate Action: </span>
                      {rec.action}
                    </div>
                  </div>
                )}
              </div>

              {/* Estimated Impact Footer */}
              {rec.estimatedImpact && (
                <div className="mt-3 pt-3 border-t border-surface-100 flex items-center justify-between text-2xs">
                  <span className="text-surface-400">Projected Benefit:</span>
                  <span className="font-bold text-emerald-600 inline-flex items-center gap-1">
                    <Zap className="w-3 h-3 text-amber-500 fill-amber-500" />
                    {rec.estimatedImpact}
                  </span>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
