export const students = [
  {
    id: 1,
    enrollmentNo: "2023CS001",
    name: "Rahul Sharma",
    email: "rahul.sharma@college.edu",
    phone: "9876543210",
    department: "Computer Science",
    course: "B.Tech",
    semester: 5,
    batch: "2023",
    cgpa: 8.65,
    placementStatus: "Eligible",
    skills: ["React", "Node.js", "Python", "SQL"],
    address: "123 MG Road, Delhi",
    resumeStatus: "Uploaded",
    linkedin: "linkedin.com/in/rahulsharma",
    github: "github.com/rahulsharma",
    placedAt: null,
    package: null,
  },
  {
    id: 2,
    enrollmentNo: "2023IT014",
    name: "Anjali Singh",
    email: "anjali.singh@college.edu",
    phone: "9876500001",
    department: "Information Technology",
    course: "B.Tech",
    semester: 5,
    batch: "2023",
    cgpa: 9.12,
    placementStatus: "Placed",
    skills: ["Java", "Spring Boot", "MySQL", "Docker"],
    address: "45 Park Street, Mumbai",
    resumeStatus: "Uploaded",
    linkedin: "linkedin.com/in/anjalisingh",
    github: "github.com/anjalisingh",
    placedAt: "TCS",
    package: "7.5 LPA",
  },
  {
    id: 3,
    enrollmentNo: "2023ME022",
    name: "Vikram Patel",
    email: "vikram.patel@college.edu",
    phone: "9123456789",
    department: "Mechanical Engineering",
    course: "B.Tech",
    semester: 5,
    batch: "2023",
    cgpa: 7.80,
    placementStatus: "Not Eligible",
    skills: ["AutoCAD", "SolidWorks", "MATLAB"],
    address: "78 Ring Road, Ahmedabad",
    resumeStatus: "Not Uploaded",
    linkedin: "",
    github: "",
    placedAt: null,
    package: null,
  },
  {
    id: 4,
    enrollmentNo: "2022CS045",
    name: "Priya Mehta",
    email: "priya.mehta@college.edu",
    phone: "9988776655",
    department: "Computer Science",
    course: "B.Tech",
    semester: 7,
    batch: "2022",
    cgpa: 9.45,
    placementStatus: "Placed",
    skills: ["Machine Learning", "Python", "TensorFlow", "AWS"],
    address: "12 Sector 5, Noida",
    resumeStatus: "Uploaded",
    linkedin: "linkedin.com/in/priyamehta",
    github: "github.com/priyamehta",
    placedAt: "Google",
    package: "24 LPA",
  },
  {
    id: 5,
    enrollmentNo: "2022EC033",
    name: "Arjun Verma",
    email: "arjun.verma@college.edu",
    phone: "9111222333",
    department: "Electronics",
    course: "B.Tech",
    semester: 7,
    batch: "2022",
    cgpa: 8.20,
    placementStatus: "Eligible",
    skills: ["Embedded C", "VLSI", "Arduino", "IoT"],
    address: "56 Civil Lines, Jaipur",
    resumeStatus: "Uploaded",
    linkedin: "linkedin.com/in/arjunverma",
    github: "",
    placedAt: null,
    package: null,
  },
  {
    id: 6,
    enrollmentNo: "2024CS003",
    name: "Sneha Kapoor",
    email: "sneha.kapoor@college.edu",
    phone: "9444555666",
    department: "Computer Science",
    course: "B.Tech",
    semester: 3,
    batch: "2024",
    cgpa: 8.90,
    placementStatus: "Not Eligible",
    skills: ["C++", "Data Structures", "HTML", "CSS"],
    address: "34 Andheri West, Mumbai",
    resumeStatus: "Not Uploaded",
    linkedin: "",
    github: "github.com/snehakapoor",
    placedAt: null,
    package: null,
  },
  {
    id: 7,
    enrollmentNo: "2022IT018",
    name: "Rohit Joshi",
    email: "rohit.joshi@college.edu",
    phone: "9777888999",
    department: "Information Technology",
    course: "B.Tech",
    semester: 7,
    batch: "2022",
    cgpa: 7.55,
    placementStatus: "Eligible",
    skills: ["PHP", "Laravel", "MySQL", "JavaScript"],
    address: "90 Banjara Hills, Hyderabad",
    resumeStatus: "Uploaded",
    linkedin: "linkedin.com/in/rohitjoshi",
    github: "github.com/rohitjoshi",
    placedAt: null,
    package: null,
  },
  {
    id: 8,
    enrollmentNo: "2023CS078",
    name: "Nisha Gupta",
    email: "nisha.gupta@college.edu",
    phone: "9222333444",
    department: "Computer Science",
    course: "MCA",
    semester: 3,
    batch: "2023",
    cgpa: 9.00,
    placementStatus: "Placed",
    skills: ["React", "TypeScript", "GraphQL", "MongoDB"],
    address: "67 Koramangala, Bangalore",
    resumeStatus: "Uploaded",
    linkedin: "linkedin.com/in/nishagupta",
    github: "github.com/nishagupta",
    placedAt: "Infosys",
    package: "9.5 LPA",
  },
]

export const studentApiResponse = {
  success: true,
  data: students,
}