import {
  CheckCircle2,
  Clock3,
  Download,
  FileText,
} from "lucide-react";

import { formatCertificateDate } from "../../utils/certificateHelpers";

import {
  DOWNLOAD_STATUS,
} from "../../constants/certificateConstants";

/**
 * Display certificate download history.
 *
 * Download history items are generated by the certificate
 * service from the approved certificate data.
 *
 * Supported fields:
 * - certificateId
 * - downloadedAt
 * - status
 *
 * @param {Object} props
 * @param {Array} props.downloadHistory
 * @param {string} props.className
 * @returns {JSX.Element}
 */
const DownloadHistory = ({
  downloadHistory = [],
  className = "",
}) => {
  const getStatusConfig = (status) => {
    if (
      String(status).toLowerCase() ===
      DOWNLOAD_STATUS.SUCCESS.toLowerCase()
    ) {
      return {
        label: "Downloaded",
        icon: CheckCircle2,
        classes:
          "border-emerald-100 bg-emerald-50 text-emerald-700",
      };
    }

    if (
      String(status).toLowerCase() ===
      DOWNLOAD_STATUS.DOWNLOADING.toLowerCase()
    ) {
      return {
        label: "Downloading",
        icon: Clock3,
        classes:
          "border-amber-100 bg-amber-50 text-amber-700",
      };
    }

    return {
      label: "Failed",
      icon: Clock3,
      classes:
        "border-red-100 bg-red-50 text-red-700",
    };
  };

  if (!Array.isArray(downloadHistory)) {
    return null;
  }

  if (downloadHistory.length === 0) {
    return (
      <div
        className={`rounded-2xl border border-slate-200 bg-white px-5 py-8 text-center shadow-sm sm:px-6 sm:py-10 ${className}`}
      >
        <div className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100 text-slate-500 sm:h-12 sm:w-12">
          <Download
            className="h-5 w-5 sm:h-6 sm:w-6"
            aria-hidden="true"
          />
        </div>

        <h3 className="mt-4 text-sm font-bold text-slate-900 sm:text-base">
          No download history
        </h3>

        <p className="mx-auto mt-1.5 max-w-sm text-xs leading-5 text-slate-500 sm:text-sm">
          Certificate downloads will appear here once you download a certificate.
        </p>
      </div>
    );
  }

  return (
    <section
      className={`w-full rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}
    >
      <div className="border-b border-slate-100 p-4 sm:p-5">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-700 sm:h-11 sm:w-11">
            <Download
              className="h-5 w-5"
              aria-hidden="true"
            />
          </div>

          <div className="min-w-0">
            <h3 className="text-base font-bold text-slate-900 sm:text-lg">
              Download History
            </h3>

            <p className="mt-0.5 text-xs text-slate-500 sm:text-sm">
              Recent certificate download activity.
            </p>
          </div>
        </div>
      </div>

      <div className="divide-y divide-slate-100">
        {downloadHistory.map(
          (item, index) => {
            const config =
              getStatusConfig(item?.status);

            const StatusIcon =
              config.icon;

            const certificateId =
              item?.certificateId ||
              "N/A";

            const downloadedAt =
              item?.downloadedAt;

            return (
              <div
                key={`${certificateId}-${downloadedAt || index}`}
                className="p-4 sm:p-5"
              >
                <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                  <div className="flex min-w-0 items-start gap-3">
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-50 text-slate-500 ring-1 ring-slate-100 sm:h-10 sm:w-10">
                      <FileText
                        className="h-4 w-4 sm:h-5 sm:w-5"
                        aria-hidden="true"
                      />
                    </div>

                    <div className="min-w-0">
                      <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                        Certificate ID
                      </p>

                      <p className="mt-1 break-all font-mono text-xs font-semibold tracking-wide text-slate-700 sm:text-sm">
                        {certificateId}
                      </p>

                      <p className="mt-1 text-xs text-slate-400">
                        {downloadedAt
                          ? formatCertificateDate(
                              downloadedAt
                            )
                          : "Date unavailable"}
                      </p>
                    </div>
                  </div>

                  <span
                    className={`inline-flex w-fit shrink-0 items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-[10px] font-semibold sm:text-xs ${config.classes}`}
                  >
                    <StatusIcon
                      className="h-3.5 w-3.5"
                      aria-hidden="true"
                    />

                    {config.label}
                  </span>
                </div>
              </div>
            );
          }
        )}
      </div>
    </section>
  );
};

export default DownloadHistory;