export const APPLICATION_STATUS = {
  APPLIED: "APPLIED",
  SHORTLISTED: "SHORTLISTED",
  ASSESSMENT: "ASSESSMENT",
  TECHNICAL_INTERVIEW: "TECHNICAL_INTERVIEW",
  HR_INTERVIEW: "HR_INTERVIEW",
  SELECTED: "SELECTED",
  REJECTED: "REJECTED",
  WITHDRAWN: "WITHDRAWN",
};

export const ALLOWED_APPLICATION_TRANSITIONS = {
  [APPLICATION_STATUS.APPLIED]: [
    APPLICATION_STATUS.SHORTLISTED,
    APPLICATION_STATUS.ASSESSMENT,
    APPLICATION_STATUS.REJECTED,
    APPLICATION_STATUS.WITHDRAWN,
  ],
  [APPLICATION_STATUS.SHORTLISTED]: [
    APPLICATION_STATUS.ASSESSMENT,
    APPLICATION_STATUS.TECHNICAL_INTERVIEW,
    APPLICATION_STATUS.REJECTED,
    APPLICATION_STATUS.WITHDRAWN,
  ],
  [APPLICATION_STATUS.ASSESSMENT]: [
    APPLICATION_STATUS.TECHNICAL_INTERVIEW,
    APPLICATION_STATUS.HR_INTERVIEW,
    APPLICATION_STATUS.REJECTED,
    APPLICATION_STATUS.WITHDRAWN,
  ],
  [APPLICATION_STATUS.TECHNICAL_INTERVIEW]: [
    APPLICATION_STATUS.HR_INTERVIEW,
    APPLICATION_STATUS.SELECTED,
    APPLICATION_STATUS.REJECTED,
    APPLICATION_STATUS.WITHDRAWN,
  ],
  [APPLICATION_STATUS.HR_INTERVIEW]: [
    APPLICATION_STATUS.SELECTED,
    APPLICATION_STATUS.REJECTED,
    APPLICATION_STATUS.WITHDRAWN,
  ],
  [APPLICATION_STATUS.SELECTED]: [],
  [APPLICATION_STATUS.REJECTED]: [],
  [APPLICATION_STATUS.WITHDRAWN]: [],
};

export const INTERVIEW_STATUS = {
  SCHEDULED: "SCHEDULED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  RESCHEDULED: "RESCHEDULED",
};

export const ALLOWED_INTERVIEW_TRANSITIONS = {
  [INTERVIEW_STATUS.SCHEDULED]: [
    INTERVIEW_STATUS.IN_PROGRESS,
    INTERVIEW_STATUS.COMPLETED,
    INTERVIEW_STATUS.CANCELLED,
    INTERVIEW_STATUS.RESCHEDULED,
  ],
  [INTERVIEW_STATUS.RESCHEDULED]: [
    INTERVIEW_STATUS.SCHEDULED,
    INTERVIEW_STATUS.IN_PROGRESS,
    INTERVIEW_STATUS.COMPLETED,
    INTERVIEW_STATUS.CANCELLED,
  ],
  [INTERVIEW_STATUS.IN_PROGRESS]: [
    INTERVIEW_STATUS.COMPLETED,
    INTERVIEW_STATUS.CANCELLED,
  ],
  [INTERVIEW_STATUS.COMPLETED]: [],
  [INTERVIEW_STATUS.CANCELLED]: [],
};

export const INTERVIEW_ROUNDS = {
  ASSESSMENT: "ASSESSMENT",
  TECHNICAL_1: "TECHNICAL_1",
  TECHNICAL_2: "TECHNICAL_2",
  HR: "HR",
  FINAL: "FINAL",
};

export const SKILL_PRIORITY = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
};

export const ERROR_CODES = {
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_APPLICATION: "DUPLICATE_APPLICATION",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

export default {
  APPLICATION_STATUS,
  ALLOWED_APPLICATION_TRANSITIONS,
  INTERVIEW_STATUS,
  ALLOWED_INTERVIEW_TRANSITIONS,
  INTERVIEW_ROUNDS,
  SKILL_PRIORITY,
  ERROR_CODES,
};
